### ISSUE TITLE
[REQUEST] Reusing some of Knightmare's enhancements in 1.42d

### ISSUE THREAD

**Issue by BreakinBenny** [iortcw/iortcw#135] opened 2022-01-18 15:54 UTC
Knightmare's unofficial 1.42d patch (as seen [here](https://www.pcgamingwiki.com/wiki/Return_to_Castle_Wolfenstein)) in relation to the UI plus provides map scripts (.ai and norway.script) includes additional settings, can this be merged into iortcw's next version like a sort-of continuation of what that patch provided? Of course, it's only for the singleplayer mode.

...Any of the enhancements that aren't here can be added.

**Comment by MAN-AT-ARMS** [comment] 2022-01-18 20:25
I'm not aware of anything in that patch that isn't implemented in iortcw (and without modifying official game files)

**Comment by BreakinBenny** [comment] 2022-01-19 11:32
Knightmare fixed being able to abuse the Tesla and flamethrower by noclipping, leaning (a favorite given no ammo's used!), and when using these underwater, and hints showing for alarm boxes at beyond interaction distances...

An anistropic filter setting in the System menu, some extra video modes (which you already have), and then there's hardware gamma! As for the map scripts... I'm using Diff Checker for this.

**maps**
* n11down added to forest.ai, triggered if nazi10's killed. In turn, nazi11's n10down now gets triggered and his "accum" is set to 1 instead of 0.
* In norway.script, zone1_backup1 & zone_backup2 in backup_for_zone1 are commented out. (1.42d also fixes laggy AI in this map...)
* In chateau.ai, the chanting Elite Guard now waits 10 seconds between Latin chants instead of 5... **nazi2** now triggers "too_far_too_see" when he walks back inside
* cutscene maps seem to be music timing focused.

**ui**
* Sound quality can now go up to 48 khz
* Screen alignment has been added to the various menu items, but Knightmare's system.menu doesn't work with iortcw likely because while "r_ext_texture_filter_anistropic" is supported, "r_ext_texture_filter_anistropic_avail" is not. Regular WolfSP.exe works with the patch; iortcw kicks the user back to Main Menu instead. Everything else seems to be completely functional.

These files (and system.menu updated with iortcw in mind) could be in a sp_pak5.pk3

**Comment by MAN-AT-ARMS** [comment] 2022-01-19 21:52
I committed a couple of those fixes. Most of that stuff would be more for mod developers.
There are no 44 or 48kHz sound assets and the s_khz stuff was removed when sound engine was changed to modular.
Vanilla game assets (menus, maps, etc.) will not be modified nor will I require any additional paks as part of this project.
HW gamma is already part of the engine (and always has been) with the r_ignorehwgamma cvar. Default was already changed to 0 long ago so that should work without change.

**Comment by BreakinBenny** [comment] 2022-01-20 09:23
Goodie! Then what about that 1.42c fix that for the Tesla gun and flamethrower not spending ammo when fired while noclipping, leaning, or even underwater?... Would it be toggleable for purists who'd like to keep it?

**Comment by MAN-AT-ARMS** [comment] 2022-01-20 19:18
The tesla/flamethrower change was committed. No, it's not toggleable. I'm pretty sure that's not the intended behavior.

**Comment by BreakinBenny** [comment] 2022-01-21 15:15
I won't miss the buggy behavior even if it's helpful. 😋

**Closed** 2022-05-21 23:03 UTC

**Comment by IdiotBrazil** [comment] 2024-12-19 17:42
Just asking out of curiousity. If the game files dont have higher quality audio files, then how does knightmare patch have higher quality audio?

**Comment by BreakinBenny** [comment] 2024-12-19 18:15
I think it just adds an extra s_khz option, not exactly rocket science. (Don't know why someone'd care with this, unlike Raven Software as they use 44.1 kHz.)

**Comment by IdiotBrazil** [comment] 2024-12-19 18:19
Nah audio quality changes with it too, I guess it adds effect to the audio files?

**Comment by MAN-AT-ARMS** [comment] 2024-12-19 19:06
No it doesn't. All of the game assets are 22kHz regardless of that old cvar setting (which did nothing)

**Comment by IdiotBrazil** [comment] 2024-12-19 19:13
I am making this conversation longer than it is supposed to be so I am gonna be just putting this here, I think I said some things wrong so here is the audio in game.

https://github.com/user-attachments/assets/43e49680-98e9-4748-8285-f792ed8cae4e

**Comment by BreakinBenny** [comment] 2024-12-19 22:54
I think you'd notice more differences by playing RealRTCW, which has certain sounds use 44.1 Khz. If you have OpenAL enabled, `s_khz` is redundant.

**Comment by IdiotBrazil** [comment] 2024-12-20 12:43
Oh wait, I never probably understood how openal works cause I wasn't abled to find any comparison of the sound quality in iortcw. Is it something like this s_khz option?

**Comment by IdiotBrazil** [comment] 2024-12-20 13:13
Ok I just tested it and found out openal option is a better audio option like s_khz (I'm sure there are bunch of difference between them) and with that there is no reason to use knightmare patch all.

**Comment by MAN-AT-ARMS** [comment] 2024-12-20 13:47
You can also further tweak sound settings when using OpenAL by creating a config for it and placing it in the root game folder.

A sample file can be found here: 
https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample

**Comment by IdiotBrazil** [comment] 2024-12-20 13:53
I think default settings are nice, however one thing I found interesting is that the ps2 port of the game has higher quality music with 44khz quality. Someone just made a mod of it but it has audio problems with the port https://www.moddb.com/games/return-to-castle-wolfenstein/addons/high-quality-music-soundtrack

Edit: Nevermind the audio problems aren't cause of the port. Sound files are like that.
