### ISSUE TITLE
Loading a saved game while in game does not work.

### ISSUE THREAD

**Issue by MrUnbecoming** [iortcw/iortcw#44] opened 2018-05-06 01:25 UTC
So, I installed this source port, and been playing it a bit. Works great, much better than the original game, but I ran into an issue where if I load a saved game (whether it be through quick load or the load game menu in the pause menu) the ESC key doesn't work anymore, nor does the Quick Load key. As a result, I have to ALT-F4 (Since I can't press ESC to get to the quit game menu) and then relaunch the game to load my saves from the main menu. Any insight on this? Hopefully I have provided enough information to explain the problem. Thank you. 

P.S. I used one of the "releases" versions, because I am not proficient enough to compile it myself.

**Comment by uzyfeo** [comment] 2018-05-06 07:58
I tried to replicate this and am not able to.

As you didn't specified which release version did you try out, I tried latest, 1.51b 64bit Linux version (as that is what I'm currently) and it is not present on that build, arch and platform at least.

If you can, write specific version you downloaded (platform, architecture, version as I did) otherwise this seems like one-man's problem for whatever reason :/

**Comment by MrUnbecoming** [comment] 2018-05-06 16:13
thank you for the reply. I tried the latest release version, and here are my specs that I stupidly forgot to put:
Windows 10 Education x64, Version 1709, Build 16299.371
GTX 1080 
i7 4790K 
16GB RAM

I didn't do any patching for my language, because I figured that everything I needed was included in the 1.51b -win-x64 archive. I will download the patch and apply it and see. Thank you very much for your insight. (side note: I downloaded the 1.51b archive and copied and pasted it into my RTCW game directory. Are you supposed to do that, or is it standalone?)

**Comment by MrUnbecoming** [comment] 2018-05-06 16:14
@uzyfeo thank you for the reply. I tried the latest release version, and here are my specs that I stupidly forgot to put:

Windows 10 Education x64, Version 1709, Build 16299.371
GTX 1080
i7 4790K
16GB RAM

I didn't do any patching for my language, because I figured that everything I needed was included in the 1.51b -win-x64 archive. I will download the patch and apply it and see. Thank you very much for your insight. (side note: I downloaded the 1.51b archive and copied and pasted it into my RTCW game directory. Are you supposed to do that, or is it standalone?)

**Comment by MrUnbecoming** [comment] 2018-05-06 16:59
Update: I installed the patch_data141 and I am having the same issue, unfortunately.

**Comment by uzyfeo** [comment] 2018-05-06 17:33
Yep, you:
- unpack patch files to game directory
- unpack engine files to game directory

So you did all steps the way you should have... Weird :/

Well, let's try console output, shall we? :)

1. 'Shift + Right Click' on the root folder of your RTCW installation (folder where you unpacked engine files). A little different pop-up menu should appear with an option sounding like "Open command-prompt here" - click it!
2. Now enter following line there (without quotes!) "./ioWolfSP.x86_64 +seta developer 1 +seta logfile 2"
3. Game should now open in developer mode with logging to file enabled. This should print some more messages which could help identify the issue + saves them to file.
4. Now do what you did and close the game.
5. New file should appear inside "%userprofile%\Documents\RTCW\main" name "rtcwconsole.log". Attach this file here.

**Comment by uzyfeo** [comment] 2018-05-06 17:54
Just to be sure you know what to do, I quickly recorded a little clip showing what you should do to enable logging.

https://www.youtube.com/watch?v=pN1c_Y-id9Y

I don't have any software to show key presses unfortunately, but when you read what I wrote above + watch the video, you should have the idea of what I've done :)

**Comment by MrUnbecoming** [comment] 2018-05-06 18:00
Well, what is interesting is that when I performed everything, I could not load a saved game from the main menu. I tried a couple times, and it just kicks me back to main right after hitting load

**Comment by uzyfeo** [comment] 2018-05-06 18:02
Attach the log anyway if you managed to create it - there should be answers :)

**Comment by MrUnbecoming** [comment] 2018-05-06 18:06
I was able to delete the wolfconfig.cfg in documents/RTCW/main (I backed it up often) and that fixed the issue with being unable to load. I will try to generate the logfile again. It did create it, but I want to see if that is what caused it to be unable to load from main menu.

**Comment by uzyfeo** [comment] 2018-05-06 18:27
Oh, sorry...
I mixed commands (realised it just now as I saw the log... lol :( )

Try to run it with just "+seta logfile 1"
This should capture whole input and not just errors. 

I forgot that "+seta developer 1" actually prevents save game loading, that's normal...
Also, setting logfile to 2 instead of 1 just outputs error messages and we are interested in whole output so this should be the way to go :)

**Comment by MrUnbecoming** [comment] 2018-05-06 18:45
OK here is the new log. No problem with mixing up the commands haha
[rtcwconsole.log](https://github.com/iortcw/iortcw/files/1977918/rtcwconsole.log)

**Comment by uzyfeo** [comment] 2018-05-06 18:59
There seems to be nothing out of ordinary :/

Funny thing is that your log doesn't contains data related to OpenAL, etc. in the beginning after loading pak files and before changing level - it should be there as far as I know (I have it there at least...) along with extensions available by your GPU.

There are few warnings but they are normal and not critical in any way, as they are problems present in base game (I have them patched in my repo, but nonetheless, as I stated, they are no problem so this is out...)

Other than this, I can't seem to find anything out of place in any way :/

I'll compile fresh latest executables for you and let's see how far this will get us (maybe it was some issue that has been patched in the meantime, but I can't find it in commit history...)
If this doesn't help than maybe @MAN-AT-ARMS will know something I don't when he reads this :)

Uploading shortly...

**Comment by uzyfeo** [comment] 2018-05-06 19:18
Here it is:
[rtcw-latest.zip](https://github.com/iortcw/iortcw/files/1977942/rtcw-latest.zip)

If this don't fix the issue than I'm out of ideas :/

**Comment by uzyfeo** [comment] 2018-05-06 20:00
And now he pushes... :D 
Oh well, I'll recompile it as it seems you didn't saw the message yet (or didn't respond at least...)

**Comment by MrUnbecoming** [comment] 2018-05-06 20:03
@uzyfeo I was out cutting the lawn ahaha. Thanks I really appreciate you compiling it for me!

**Comment by uzyfeo** [comment] 2018-05-06 20:04
No problem mate :P 

So here is the absolute latest version from what he pushed half an hour ago. Hopefully it will work now :X

[rtcw-latest.zip](https://github.com/iortcw/iortcw/files/1977991/rtcw-latest.zip)

**Comment by MrUnbecoming** [comment] 2018-05-06 20:06
@uzyfeo alright, I'll give it a whirl!

**Comment by MrUnbecoming** [comment] 2018-05-06 20:18
OK so I did what I said above, and as expected, I can't load a game due to changes in the way the source port handles save files. However, I did start a new game, save, and then I was able to load normally ingame. Does this help at all?

**Comment by uzyfeo** [comment] 2018-05-06 20:19
Oh well, I'm totally out of ideas then. :(

As I said in absolutely first post, this seems to be kind of local, dunno why and what causes it. This is rather strange and random issue to have :/

Absolutely last idea is - bad driver maybe? (out of date, or just erroneous)
At least your system seems to be out of date (as I just opened Windows Update and it seems 1803 is out).

If you have latest GPU drivers, etc. (apart from system :P ) then I really don't know as you have GPU from same family as me (I own GTX 1050) so we share same drivers and yet the issue at hand is not present on my machine :/

Hope you can sort it out somehow with someone else than. :(

**Comment by uzyfeo** [comment] 2018-05-06 20:34
Oh... Oh well... RIP :/
I misread what you wrote, yeah...

Well, loading save from this version in original is kind-of expected to fail, as this version is different from the original in quite a few ways.
Opposite way should work 90% of the time though (and as it seems, it is).

Anyway, as I said, I unfortunately can't help you any further.
Logs look clean, version you are running is the latest available so there's not much help I can give now :(

**Comment by MrUnbecoming** [comment] 2018-05-06 21:15
yeah I figured that running the new version save in the old version wouldn't work, but I wanted to try it. Anyways, thanks for all the help. Maybe I'll wait and see if @MAN-AT-ARMS can do anything about this. I also wonder why it works on your system and not on mine :/

**Comment by MAN-AT-ARMS** [comment] 2018-05-06 23:25
I'm not home at the moment but you can't load 32 bit saves with a 64 bit client (or vice versa) if that's what you're trying to do

**Comment by MrUnbecoming** [comment] 2018-05-07 06:11
Yes, that was a separate thing that I did to determine if it was the custom engine that was the problem, or if it was something to do with my installation of the game. Since regular RTCW loads correctly, it leads me to believe there is something with the custom engine that is off. Anyways, in hindsight, mentioning the aspect of loading a save with the original game only served to confuse everyone, so that was stupid to say. The original problem is that when I use the source port to load a save game (that I created within the source port) it does not load while ingame. It works fine in the main menu, but if I load ingame it causes ESC to stop working. I tried binding MENU to another key, and it is the same issue. After the menu key stops working, I can do anything besides open the menu. So I can still shoot, walk, etc. But since I can't load or save after that, it makes the most sense to alt-F4. Hopefully this clears up what I was trying to say.

**Comment by MAN-AT-ARMS** [comment] 2018-05-07 07:08
Try backing up or deleting any old configs and try using a fresh config. This includes any configs you have from the vanilla client which are usually located in the "Main" folder of Program Files/Return to Castle Wolfenstein

**Comment by MAN-AT-ARMS** [comment] 2018-05-07 13:09
Where is your vanilla game installed? The config for that will not be in the Documents folder.

**Comment by MrUnbecoming** [comment] 2018-05-07 13:29
well there I showed that I deleted the vanilla and the base game configs

**Comment by MrUnbecoming** [comment] 2018-05-07 15:31
It's the GOG version, the guy who was helping me said to set logfile to 1 so that is why the log is incomplete I guess? It is the 64-bit client (and 64 bit windows) EN_US keyboard layout. The problem is that when I save through the menu and then click "load game" through the menu (while in game) I cannot open the menu again, nor can I Quick Load. Everything else works as normal, though.

**Comment by MrUnbecoming** [comment] 2018-05-07 15:36
New log file for you. I launched it using the +seta logfile 2       command line parameter.
[rtcwconsole.log](https://github.com/iortcw/iortcw/files/1980493/rtcwconsole.log)

**Comment by MAN-AT-ARMS** [comment] 2018-05-07 15:49
What do you have in this directory? Path is shown in rtcwconsole.log file...

c:/steam\SteamApps\common\Return To Castle Wolfenstein\main


Side note: You should be using the OpenAL32.dll file that came with the 1.51b release and it should be in the same directory as the .exe files..
If you have one in C:\Windows\System32 you should probably replace that one as well. That version is ancient.

**Comment by MrUnbecoming** [comment] 2018-05-07 16:12
I actually have nothing in there. The directory doesn't exist, so I don't know why that was in the log file. I saw that myself, too. Alright I will do that with the OpenAL file.

**Comment by uzyfeo** [comment] 2018-05-07 16:35
Wow, this didn't work before!
Look at the absolute first log - only error messages :/

Yeah, OpenAL is likely candidate here.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrUnbecoming** [comment] 2018-05-07 16:36
I have an update that will maybe help. I played normally, and did a quick save along with a regular save. I opened the menu and loaded the quick save through the LOAD menu (NOT with F9) That worked fine, and loaded my quicksave through the menu. I played a bit again and tried to load the REGULAR save, through the menu again. Did not work, same issue as before. Here is another log file if that helps at all.
[rtcwconsole.log](https://github.com/iortcw/iortcw/files/1980652/rtcwconsole.log)

**Comment by MrUnbecoming** [comment] 2018-05-07 16:40
@uzyfeo yeah that is wierd. I did the command you asked in your initial post to the T. I copied and pasted it into cmd (and modified it a little, since there was a forward slash where a backslash should have been) so I don't know why it did what you initially wanted when @MAN-AT-ARMS asked me to do it lmao.

**Comment by MrUnbecoming** [comment] 2018-05-07 16:51
well sorry for the comment spam, but I found something else. I deleted all of my saves, started from the beginning and saved. It works fine now... I don't really want to start from the beginning tbh, so I guess I'll just live with it. What could have caused this in the first place? I still can't load my old saves ingame, but I can quick-load.

**Comment by MrUnbecoming** [comment] 2018-05-07 16:58
OK OK. I have 100% found the problem. I loaded my regular save from the menu, and played a bit. I saved NORMALLY in PAUSE MENU and played. Loaded, and it worked fine. HOWEVER. I made another save file and called it what it as called before "1234". Do you think that having only numbers in the name caused this? Because so far only having string characters has worked, and after trying to load 1234 it fails as it did before and I have to alt-f4. I tested some more, and it seems that having any numbers in the name of the save breaks it for whatever reason. Try it for me.

**Comment by MAN-AT-ARMS** [comment] 2018-05-07 20:04
Your old saves will not work with the 64 bit client. Use the 32 bit client if you want to use your saves from the vanilla client.

**Comment by MrUnbecoming** [comment] 2018-05-08 04:44
Well I know the old saves won't work, these are all saves I made with the 64-bit source port for testing purposes. Did you try reproducing the issue by placing a number into the name of a save game when going to save? Because I determined as I said above that that was the issue for some reason. Odd, but it is reproducible.

**Comment by MAN-AT-ARMS** [comment] 2018-05-08 06:52
Yeah I was able to reproduce the issue with the save files containing numbers.

**Comment by MrUnbecoming** [comment] 2018-05-09 01:08
Is that something you can look into fixing? I am surprised that noone else has discovered and reported this.  Thanks for listening by the way. It was probably frustrating, but I found the problem anyway

**Comment by MAN-AT-ARMS** [comment] 2018-05-09 01:31
Yeah it's an odd problem. I'll look into it

**Comment by uzyfeo** [comment] 2018-05-09 07:09
@MrUnbecoming I found far more odd ones when I came here :D
Like the one when you couldn't kick (like ingame kick, not kicking player.. ) on Windows because of broken OpenAL library :D 

But yeah, kinda funny that nobody reported this one as of yet...

Maybe it is platform-specific to Windows or something, who knows... I bet most people play this source port on Mac and Linux, as there are no native executables right from ID Software for these platforms.

Anyway, glad it kind of got sorted out :)

**Comment by MrUnbecoming** [comment] 2018-05-10 16:45
Isn't openAL solely a sound library ? That's really wierd that it would prevent kicking. Yeah my issue could be platform-specific, who knows. It would be appreciated if you could test it too, since we would be able to nail down better what would cause it.

**Comment by MAN-AT-ARMS** [comment] 2018-05-10 21:03
It's not platform or architecture specific. I was able to reproduce it on 32bit and 64 bit Linux and Mac.
The save filename is valid and saved but something seems to be missing. The map_restart is not called. Loading just ends with a servercommand for cast state. Still trying to track down the issue.

**Comment by MrUnbecoming** [comment] 2018-05-10 21:17
oh I see. I'm just really surprised it wasn't discovered until now. I guess I am the only idiot who just types "1234" as the save file name. I couldn't be arsed to name it properly when I started the game initially.

**Comment by MAN-AT-ARMS** [comment] 2018-05-11 00:19
Should be fixed in 0c9b0d0.
I don't think this bug was limited to this engine...was probably always broken.

**Comment by uzyfeo** [comment] 2018-05-17 06:35
Here is latest build:
[iortcw-latest.zip](https://github.com/iortcw/iortcw/files/2011866/iortcw-latest.zip)

**Comment by uzyfeo** [comment] 2018-05-17 06:46
I can confirm that the fix worked.

**Comment by MrUnbecoming** [comment] 2018-05-17 22:52
Oh it's based on Quake 3? Oh wow I thought all this time it was based on the RTCW one. That makes this an even more impressive project from my perspective. I will just test it real quick myself and see. Hats off to you guys for fixing it. And thank you @uzyfeo that's probably the last build I'll ever need, since this was the only problem I've found in like 4-5 hours.

**Comment by MAN-AT-ARMS** [comment] 2018-05-17 23:59
It's not based on the Quake3 source release. It's based on RTCW source. The two are very similar engines. The changes made to the source are mostly the engine fixes from ioq3, with some RTCW specific stuff too.

**Closed by MAN-AT-ARMS** 2018-05-17 23:59 UTC
