### ISSUE TITLE
AI mg42 aiming bug

### ISSUE THREAD

**Issue by wolfetplayer** [iortcw/iortcw#100] opened 2020-09-22 18:33 UTC
AI cant aim stationary mg42 properly.
Compared code with vanilla, some lines were missing.
Fixed it in realrtcw. Take a look:
https://github.com/wolfetplayer/RealRTCW/commit/71d87245300ec47c38946a4d595b1aba38641d06

**Comment by MAN-AT-ARMS** [comment] 2020-09-22 19:05
Removed because variable is never used in the function

**Comment by wolfetplayer** [comment] 2020-09-22 19:37
fixed the bug somehow though

**Comment by MAN-AT-ARMS** [comment] 2020-09-22 19:56
Don't see how it would...Can you describe when and where the bug occurs in the game so I can try and reproduce?

**Comment by wolfetplayer** [comment] 2020-09-22 20:02
Sure. 
Loadup the "factory" map.
Get yourself a god mode.
There is a nazi who will mount an mg42 once you exit the canalization(give him some time he will mount it eventually)
After that he will start shooting.
But it seems he just cant turn the mg in any direction. So he will just shoot in one available direction.
This is what happens on iortcw.
Load up the same map on vanilla and mg gunner will freely aim at player.

**Comment by MAN-AT-ARMS** [comment] 2020-09-22 20:07
See if the change on line 4115 (commented out line) is the only line that needs changed. The others...I don't see how they would be needed.

**Comment by MAN-AT-ARMS** [comment] 2020-09-22 21:30
I just tested it. Only that one line needs changed

**Comment by MAN-AT-ARMS** [comment] 2020-09-22 21:36
Fixed in efd2657

**Closed** 2020-09-23 18:37 UTC
