### ISSUE TITLE
cg_autoactivate bug

### ISSUE THREAD

**Issue by donizettilorenzo** [iortcw/iortcw#10] opened 2016-01-06 12:57 UTC
I have cg_autoactivate set to  "0" but it's not working (items are gathered automatically)

**Comment by MAN-AT-ARMS** [comment] 2016-01-06 21:16
I'm not able to reproduce this behavior. Check your config.

**Comment by donizettilorenzo** [comment] 2016-01-06 21:27
Here's a video (with cg_autoactivate in console showing its "0") and see the second medkit behaviour: http://www46.zippyshare.com/v/Uw1ceGvR/file.html

**Comment by MAN-AT-ARMS** [comment] 2016-01-06 21:46
OK...so did you check your config?
I'm not able to reproduce the behavior. Posting a video is not helpful at all.

**Comment by donizettilorenzo** [comment] 2016-01-06 21:47
Yes, I did check, and I simply can't explain why!

**Comment by MAN-AT-ARMS** [comment] 2016-01-06 21:52
How about posting your config or a console log or something?

**Comment by MAN-AT-ARMS** [comment] 2016-12-15 09:42
Closing due to lack of information. Was not able to reproduce this with iortcw game modules.

**Closed by MAN-AT-ARMS** 2016-12-15 09:42 UTC
