### ISSUE TITLE
OSX compilation issues

### ISSUE THREAD

**Issue by Jarvik7** [iortcw/iortcw#1] opened 2015-03-24 01:31 UTC
Is there a specific reason why so many libraries are included in the repo instead of compiling using system libs like most other idtech source ports? Due to the SP/MP split all are included twice, in fact.

On OSX this is creating a conflict with user installed openal-soft that results in a crash on iortcw startup unless it is uninstalled or USE_OPENAL_DLOPEN is set to 0 in the makefile.

Compiling with USE_LOCAL_HEADERS=0 is also broken due to the header path being wrong (does not include "SDL2/"). It only disables SDL2 and OpenAL local headers too, libcurl libogg libvorbis opus libjpeg etc are all still internal.

I have created a fork and will work on removing all 3rd party libs/headers from the repo. Once I am done I will create a pull request.

**Comment by MAN-AT-ARMS** [comment] 2015-03-24 01:40
The libraries are for VOIP. There is an openal-soft library for OSX included in code/libs/macosx

Don't bother with the pull request, it won't be merged.

**Comment by Jarvik7** [comment] 2015-03-24 01:50
Ok, I will maintain it as a separate fork if that is the case.
An openal-soft OSX lib is included in the repo yes, but as I said, it crashes on start if the system already has openal-soft on it.

I am aware that libraries are for things (like VOIP), but there is no good reason to maintain 3rd party headers & libs in the repo.

**Comment by MAN-AT-ARMS** [comment] 2015-03-24 01:54
They're libs and headers are used for building other platforms and features. 
The included libraries are intended to sit alongside the game binaries, as it's the first place it's looked for. It should not conflict with any other versions on the system.

**Comment by Jarvik7** [comment] 2015-03-24 02:01
And yet it is conflicting. The same binary will run fine once openal-soft is removed from /usr/local/libs.

I am not proposing rewriting code to not use external libs. I am proposing to compile using libs in the compiler's search path instead of maintaining them in-repo.

**Comment by zturtleman** [comment] 2015-03-24 02:27
`make USE_INTERNAL_LIBS=0` will use system libraries/headers.

**Comment by Jarvik7** [comment] 2015-03-24 02:37
That forces USE_LOCAL_HEADERS=0, which causes compilation to fail due to an incorrect SDL2 path (it's missing the "SDL2/" prefix in all the files that include SDL2 headers).

It's interesting that ioquake3 source does not have these issues.

**Comment by MAN-AT-ARMS** [comment] 2015-03-24 09:57
Can you give me some more details about what OSX this is, compiler version, what commands you're using to build etc? I'll see if I can reproduce it.

**Comment by Jarvik7** [comment] 2015-03-24 12:25
OSX 10.10.2
Xcode 6.2 (Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn))

Compiling with make-macosx_xcode5.sh x86_64
Bug 1) It will not compile
Fix) Comment out line 55 of code/game/g_func_decs.h

openal-soft is installed using Homebrew.

Bug 2) Compiling with the makefile as-is results in a crash on launching the .app.
Workaround 1) Uninstall system version of openal-soft
Workaround 2) Set USE_OPENAL_DLOPEN=0 in Makefile (results in linking against OS X openal.framework, not openal-soft)

Bug 3) Compiling with USE_LOCAL_HEADERS results in a compiler error
Fix) SDL2 and Opus headers should be located with pkg-config, as they are not in the same place in Win32 as in *nix

**Comment by zturtleman** [comment] 2015-03-25 00:20
USE_CODEC_OPUS enables playing Ogg Opus (.opus) audio files too, not only VoIP. It's not required for the original game, but mods/addons could use it. VoIP is saved in demos, which allows adding commentary.

**Comment by MAN-AT-ARMS** [comment] 2015-03-25 00:50
Yes...I guess curl could be disabled by default. It was only left on for consistency or possible "thin client" support. It is also used for RTCW Coop.

Bug 1) Is fixed (only seemed to be an issue on XCode 6, but not 5 and lower). Not sure why.
Bug 2) I'm not sure there is any real reason to change that as most Mac users will not have a 3rd party OpenAL library or framework.
Bug 3) USE_LOCAL_HEADERS=0 I have to look into a little more. 
Most Mac users will not have pkg-config, etc. Your setup is not exactly the norm for Mac users.
Bug 4) I haven't tried with non-internal SDL but the console works fine for me.

**Comment by Jarvik7** [comment] 2015-03-25 01:21
Thanks for the last 2 commits. Re: the remaining bugs:

2) Most users provided with a binary may not have a system openal-soft, but if they do they will be the least likely to find a solution as no error or console message is given. One must examine the system dump and notice that there is a null pointer exception in the openal lib to find the cause.

On the other hand, most users who self-compile may very likely have openal-soft. In any case, the fact that iortcw won't even run if it's on the system is clearly a bug (which does not affect ioquake3 or any other games that use openal I've tried). Also, even though USE_OPENAL_DLOPEN=0 works, using local headers with the system lib is probably not a safe thing to do.

3) Most binary end users won't have pkg-config of course, but most people who compile code from the internet will, as it's a common dependency. I think pretty much every OSX programmer (or even person who regularly uses the terminal) has Homebrew installed at this point. In any case, the current Makefile just results in a compiler error.

4) I should clarify. With internal SDL2 the console works fine. Only external (USE_LOCAL_HEADERS=0) is broken.

**Comment by MAN-AT-ARMS** [comment] 2015-03-26 01:18
Can you check and see if it works any better for you on newest Makefiles?

**Comment by Jarvik7** [comment] 2015-03-26 02:05
Looks nice, I'll take a look when I get home from work.

**Comment by Jarvik7** [comment] 2015-03-26 02:21
Just noticed a potential issue (line 523-524):
+ CLIENT_LIBS += -framework OpenAL
+ CLIENT_EXTRA_FILES += $(LIBSDIR)/macosx/libopenal.dylib

This will link the Apple OpenAL lib from the framework, but copy the repo's openal-soft lib during the build.

This code path is run when USE_OPENAL_DLOPEN=0, USE_INTERNAL_LIBS=1, so the local libopenal.dylib should be linked instead of the external framework.

**Comment by MAN-AT-ARMS** [comment] 2015-03-26 02:53
It should be OK for right now.

**Comment by Jarvik7** [comment] 2015-03-27 02:38
Tried a few patterns..

0) Default makefile: crashes on launch (OpenAL conflict)
Strangely, disabling opus/voip in the makefile will make this work, even with USE_OPENAL_DLOPEN=1 and the system openal-soft installed.

1) USE_OPENAL_DLOPEN=0
Links against Apple OpenAL framework (while using internal header files) instead of the internal lib copied into the .app, but works fine regardless.

2) USE_OPENAL_DLOPEN=0, USE_INTERNAL_LIBS=0
Compiler error - can't find headers for Opus. Opus/Opusfile headers are in a subdirectory of the system include folder ("opus/"). Unfortunately pkg-config doesn't know about Opus/Opusfile, so it'll need to be hardcoded.

3) USE_OPENAL_DLOPEN=0, USE_INTERNAL_LIBS=0, USE_CODEC_OPUS=0
Still tries to compile with Opus and fails. VOIP depends on Opus I'm assuming, but the Makefile should print out a warning that it is re-enabling Opus. 

4) USE_OPENAL_DLOPEN=0, USE_INTERNAL_LIBS=0, USE_CODEC_OPUS=0, USE_VOIP=0
-Opus properly excluded now. Compilation works.
-Deleting the code/libs dir results in "cp: code/libs/macosx/*.dylib: No such file or directory" errors. It's trying to copy libs into the .app we aren't using. Not a big deal though.
-Game runs but only dead keys seem to work in console. Y/N on the quit screen also do not work.
-Played through level 1 with no problems, but after spawning in level 2 mouse look did not work (click to shoot and menus worked fine)
-Note: Links against user-installed OpenAL-soft in /usr/local/lib (not Apple Framework).

**Comment by wtfbbqhax** [comment] 2016-11-16 15:59
@MAN-AT-ARMS btw, i fixed several of these issues in ioq3's Makefile a while back.

**Comment by MAN-AT-ARMS** [comment] 2016-11-16 19:15
...and broke PPC. The changes were partially committed.

**Closed** 2022-05-21 23:05 UTC
