### ISSUE TITLE
Problem with menu transition

### ISSUE THREAD

**Issue by revelator** [iortcw/iortcw#63] opened 2018-08-27 05:25 UTC
Hello, game Works pretty great with iortcw besides one gripe.
When loading a new mission the arrow that is supposed to pop in at the lower corner is missing so i have to click bllindly hoping to hit it. This does not allways Work however.
It only seems to happen when using rend2.

**Comment by MAN-AT-ARMS** [comment] 2018-08-27 11:57
What OS / version are you using? Post the contents of rtcwconsole.log file. (Add +set logfile 2 to your commandline or edit the value manually with a text editor in your wolfconfg.cfg file to create this file.)

**Comment by revelator** [comment] 2018-08-31 07:40
Sorry for the late reply, been away.
Win 7 64.

> logfile opened on Fri Aug 31 09:38:12 2018

Bypassing CD checks
----- Client Initialization -----
Cmd_AddCommand: map_restart already defined
----- Initializing Renderer ----
Trying to load "renderer_sp_rend2_x64.dll" from "F:\Games\Return to Castle Wolfenstein - Platinum Edition"...
---- Renderer Initialization Complete ----
RTCWKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.778
...setting mode -2: 1920 1080
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '1280x720 1360x765 1366x768 1600x900 1920x1080 2560x1440 3200x1800 1360x768 1280x768 1280x800 1440x900 1680x1050 720x480 640x480 800x600 1024x768 1280x960 1360x1024 720x576 1280x1024'
GL_RENDERER: AMD Radeon (TM) R9 390 Series
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...GL_S3_s3tc not found
...ignoring GL_EXT_texture_filter_anisotropic
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...using GL_ARB_texture_float
...using GL_ARB_depth_clamp
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 4.50
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...ignoring GL_ARB_texture_compression_rgtc
...ignoring GL_ARB_texture_compression_bptc
...using GL_EXT_direct_state_access
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 318 GLSL shaders (192 gen 84 light 42 etc) in  3.47 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "OpenAL64.dll"...
Allocated 128 sources.
OpenAL default capture device is 'OpenAL Soft on Mikrofon (Realtek High Definition Audio)'
OpenAL capture device opened.
OpenAL info:
  Vendor:         OpenAL Community
  Version:        1.1 ALSOFT 1.17.2
  Renderer:       OpenAL Soft
  AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_pause_device
  Device:         OpenAL Soft on 6 - Philips FTV (AMD High Definition Audio Device)
  Available Devices:
OpenAL Soft on 6 - Philips FTV (AMD High Definition Audio Device)
OpenAL Soft on Realtek Digital Output(Optical) (Realtek High Definition Audio)
OpenAL Soft on Realtek Digital Output (Realtek High Definition Audio)
OpenAL Soft on Højttalere (Realtek High Definition Audio)
  Input Device:   OpenAL Soft on Mikrofon (Realtek High Definition Audio)
  Available Input Devices:
OpenAL Soft on Mikrofon (Realtek High Definition Audio)
Sound initialization successful.
--------------------------------
--- Common Initialization Complete ---
Winsock Initialized
Hostname: Revelator-Pc
IP6: fe80::51a:8547:61b:dd3f%13
IP: 192.168.87.105
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
sv_maxclients will be changed upon restarting.
------ Server Initialization ------
Server: church
RE_Shutdown( 0 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
Current search path:
C:\Users\Revelator\Documents\RTCW\main
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_vpak7.pk3 (47 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_vpak6.pk3 (493 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_vpak5.pk3 (661 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_rend2_shaders0.pk3 (5 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_pak5.pk3 (174 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_pak4.pk3 (21 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_pak3.pk3 (14 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_pak2.pk3 (232 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\sp_pak1.pk3 (1342 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main\pak0.pk3 (4775 files)
F:\Games\Return to Castle Wolfenstein - Platinum Edition\main

handle 1: rtcwconsole.log
----------------------
7764 files in pk3 files
Gametype changed, clearing session data.
------- BotLib Initialization -------
------------ Map Loading ------------
trying to load maps/church_b0.aas
loaded maps/church_b0.aas
trying to load maps/church_b1.aas
loaded maps/church_b1.aas
-------------------------------------
AAS initialized.
AAS initialized.
-----------------------------------
RE_Shutdown( 0 )
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 318 GLSL shaders (192 gen 84 light 42 etc) in  0.29 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
----- finished R_Init -----
LOADING... collision map
LOADING... sounds

.........................
Initializing Sound Scripts
...loading 'sound/scripts/cutscene1.sounds'
...loading 'sound/scripts/cutscene6.sounds'
...loading 'sound/scripts/cutscene9.sounds'
...loading 'sound/scripts/cutscene11.sounds'
...loading 'sound/scripts/cutscene14.sounds'
...loading 'sound/scripts/cutscene19.sounds'
...loading 'sound/scripts/escape1.sounds'
...loading 'sound/scripts/escape2.sounds'
...loading 'sound/scripts/tram.sounds'
...loading 'sound/scripts/village1.sounds'
...loading 'sound/scripts/crypt1.sounds'
...loading 'sound/scripts/crypt2.sounds'
...loading 'sound/scripts/church.sounds'
...loading 'sound/scripts/boss1.sounds'
...loading 'sound/scripts/forest.sounds'
...loading 'sound/scripts/rocket.sounds'
...loading 'sound/scripts/assault.sounds'
...loading 'sound/scripts/sfm.sounds'
...loading 'sound/scripts/factory.sounds'
...loading 'sound/scripts/trainyard.sounds'
...loading 'sound/scripts/swf.sounds'
...loading 'sound/scripts/norway.sounds'
...loading 'sound/scripts/xlabs.sounds'
...loading 'sound/scripts/boss2.sounds'
...loading 'sound/scripts/dam.sounds'
...loading 'sound/scripts/village2.sounds'
...loading 'sound/scripts/chateau.sounds'
...loading 'sound/scripts/dark.sounds'
...loading 'sound/scripts/castle.sounds'
...loading 'sound/scripts/end.sounds'
...loading 'sound/scripts/ai.sounds'
...loading 'sound/scripts/general.sounds'
...loading 'sound/scripts/combat.sounds'
...loading 'sound/scripts/movers.sounds'
done.
LOADING... graphics
LOADING... maps/church.bsp
stitched 20 LoD cracks
...loaded 12546 faces, 12 meshes, 22 trisurfs, 12 flares
Total cubemaps: 114
LOADING... game media
LOADING...  - textures
LOADING...  - models
LOADING...  - weapons
LOADING...  - items
LOADING...  - inline models
LOADING...  - server models
LOADING...  - particles
LOADING...  - game media done
LOADING... flamechunks
LOADING... clients
LOADING... WolfPlayer
UI menu load time = 3 milli seconds
CL_InitCGame: 10.75 seconds
43 msec to draw all images
Com_TouchMemory: 0 msec
^3turning EXEC_NOW 'quit' into EXEC_INSERT
----- Server Shutdown (Server quit) -----
AAS shutdown.
---------------------------
----- Client Shutdown (Client quit) -----
RE_Shutdown( 1 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.
-----------------------

**Comment by revelator** [comment] 2018-08-31 07:42
I noticed a script error in there, maybe that is the cause ?, but it works with the original, or else it simply ignores it.

**Comment by MAN-AT-ARMS** [comment] 2018-09-01 04:01
Not sure which version you are using, but if its one of the release builds you might want to look at https://github.com/iortcw/iortcw/issues/32 and scroll through to end comments. If that turns out to be the issue, know that the fix is already in for it and will be part of next release.

**Comment by revelator** [comment] 2018-09-02 18:54
1.51b from here, sounds atleast plausible with that problem the other user was having, ill see what the next version brings.

**Comment by MAN-AT-ARMS** [comment] 2018-09-04 21:03
Not sure if you read this post in the other issue thread...

To workaround issues caused by DPI scaling over 100%: Right click the iowolfsp.x86.exe -> properties -> compatibility tab -> check the box for disable display scaling for high dpi settings. This will be required for all fullscreen games released before Windows Vista and many after that.

This may correct your issue if you want to to try it (without waiting for next release)

**Closed** 2020-02-24 09:17 UTC
