### ISSUE TITLE
Alt tab creates a loop

### ISSUE THREAD

**Issue by donkz** [iortcw/iortcw#26] opened 2017-01-25 03:35 UTC
Pressing alt-tab sometimes creates a vid_restart loop. It keeps going until game is shut down with either quit or task manager shutdown. Then Documents\RTCW\wolfconfig_mp.cfg must be deleted to prevent the same upon startup. There are no differences between new good and old bad wolfconfig_mp.cfg except 
cg_selectedPlayer 
cg_selectedPlayerName
variables , which should not matter

**Comment by MAN-AT-ARMS** [comment] 2017-01-26 23:10
I don't know what you mean by "new good" / "old bad" wolfconfig_mp.cfg.
If you're saying they're the same it might just mean something new isn't yet  or able to be written to it.

Where is the game installed? Is there an autoexec.cfg file or other configs being loaded from there? Is a mod being used?

What OS is it / graphics card? What resolution is being used?

Need more information on how to reproduce this.

**Comment by donkz** [comment] 2017-01-27 08:20
Correction: Keys are alt+enter
The rest i described in this video. Let me know if you need more detail. Gamemod is shrubmod (ecgn)
https://www.youtube.com/watch?v=UezPqf2KBfw&hd=1

**Comment by MAN-AT-ARMS** [comment] 2017-01-27 15:36
No video at that link

**Comment by donkz** [comment] 2017-01-28 04:01
Made it public to avoid private sharing

**Comment by donkz** [comment] 2017-01-28 04:01
Made it public to avoid all the private sharing conundrum

**Comment by MAN-AT-ARMS** [comment] 2017-01-28 07:51
The only things I see weird there is:

1.) You have a space between + and exec <config name> in your shortcut, so I don't think that is being loaded. I can't see the rest of the command line other than the connect.
2.) The resolution it is trying 1680x1033 is odd. Maybe try r_mode -2 if your monitor's native resolution is 1680x1050 (this resolution was just added as a built in mode but not sure what build you are using.)

Also, if you want to add +set logfile 2 to your command line it will generate a rtcwconsole.log file in your Documents/RTCW folder. It will be easier to tell from that what is happening.

**Comment by donkz** [comment] 2017-01-29 04:34
IRT 1. Space doesnt seem to matter. It finds the cfg back in my game folder (not user/docs/rtcw)
IRT 2. i tried r_mode -2 and that didn't avoid the issue. You can see it where i set r_mode -2 in attached log and it still tries to set 1033 height , although i have no such number anywhere. It must be calculated in code.

Attaching 2 log files of consecutive restarts. r_allowResize is 0 . I never touched it before.

[shrubmod.zip](https://github.com/iortcw/iortcw/files/737309/shrubmod.zip)

**Comment by donkz** [comment] 2017-01-29 04:49
Looks like the magic happens in https://github.com/iortcw/iortcw/blob/83af015b3e79b423a72bca263e53a7baed48627b/MP/code/sdl/sdl_glimp.c , but i cannot undestand why displayAspect variable is 1.333 when my true ratio is 1.6.... if that's related to the loop at all.

**Comment by MAN-AT-ARMS** [comment] 2017-01-29 09:31
What is the full command line? Whatever is in your config is only being latched and not set.
Can you see if the /minimize command behaves the same?

If you want to message me directly to troubleshoot this you can reach out to me on IRC.

**Comment by donkz** [comment] 2017-01-30 03:00
F:\Games\iortcw\ioWolfMP.x86_64.exe +set fs_game shrubmod  +set com_maxfps 125 +exec dcxg3.cfg +connect 64.237.36.250:27960 +set logfile 2

/minimize does not seem to produce this erratic behavior

**Comment by MAN-AT-ARMS** [comment] 2017-01-30 06:06
I was able to somewhat reproduce this issue. It seems to only affect Windows. It seems to be an SDL issue.
I committed a change to mitigate the restart loop but I need to see if I can figure out why the window borders are not drawn / accessible.

**Closed** 2017-06-08 17:40 UTC
